version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}"
    restart: always

volumes:
  portainer_data: