version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--ping=true"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: portainer
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "portainer_data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=8000"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}"
    restart: always

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PORTAINER:-/home/pi/docker_volumes/portainer_data}
